#!/bin/bash

# constants
drm_program_name="${drm_program_name} ${0##*/drm-}"

# auxiliary function to print out usage help
function drm_usage()
{
    cat <<EOF
Restores configuration of custom scripts.

BEWARE: THIS WILL DELETE ALL FILES PRESENT IN scripts/enabled DIRECTORY!

Usage: ${drm_program_name}

EOF
}

# parse arguments
drm_options_short="h"
drm_options_long="help"
drm_options=`getopt -o "${drm_options_short}" -l "${drm_options_long}" -n "${drm_program_name}" -- "${@}"`
drm_options_err=${?}
eval set -- $drm_options
while true; do
  case "${1}" in
    -h | --help)
      drm_usage
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      echo
      drm_usage
      exit 1
      ;;
  esac
done
if [ ${drm_options_err} -ne 0 ]; then
  echo
  drm_usage
  exit 1
fi

# determine script working directory
if [ "x${drm_wd}" == "x" ]; then
  drm_wd="`echo ${0} | sed -n '/\//{s/\/[^\/]*$//;p;}'`"
  drm_wd="`(cd "${drm_wd}/../..";pwd)`"
fi

# clean enabled scripts
rm ${drm_wd}/scripts/enabled/* > /dev/null 2> /dev/null

# restore defaults
cd ${drm_wd}/scripts/enabled
ln -s -v ../available/locale-en-gb-utf8.sh 10_locale-en-gb-utf8.sh
ln -s -v ../available/devel-cpp.sh 20_devel-cpp.sh
ln -s -v ../available/environment-vim.sh 30_environment-vim.sh
ln -s -v ../available/users-default.sh 40_users-default.sh
ln -s -v ../available/users-custom.sh 50_users-custom.sh


# vim: set ts=2 sw=2 et:


