#!/bin/bash

# auxiliary function to print out usage help
function drm_usage()
{
    cat <<EOF
Creates new Docker image for "rotating machine".

Usage: ${0} [options]

Options: (defaults in [brackets] after descriptions)

  --help                      print this help

  --version                   print version

  --verbose                   produce verbose output

  --dry-run                   do not execute any docker commands

  --image-name                name of docker image to be produced
                              [default: rotating-machine]

  --image-tag                 tag of docker image to be produced
                              [default: latest]

  --extra-args                any extra arguments to be passed to
                              docker run command when creating
                              new container
                              [default: <none>]

EOF
}

# determine script working directory
if [ "x${drm_wd}" == "x" ]; then
  drm_wd="`echo ${0} | sed -n '/\//{s/\/[^\/]*$//;p;}'`"
  drm_wd="`(cd "${drm_wd}/../..";pwd)`"
fi

# parameter (default) values
drm_verbose=
drm_dry_run=
drm_image_name="rotating-machine"
drm_image_tag="latest"
drm_extra_args=""

# parse arguments
for drm_arg in "${@}"; do
  drm_arg_consumed=
  if echo ${drm_arg} | grep "^--help" > /dev/null 2> /dev/null; then
    drm_usage
    exit 0
  fi
  if echo ${drm_arg} | grep "^--version" > /dev/null 2> /dev/null; then
    echo "drm-build v0.2.0"
    exit 0
  fi
  if echo ${drm_arg} | grep "^--verbose" > /dev/null 2> /dev/null; then
    drm_verbose=true
    drm_arg_consumed=true
  fi
  if echo ${drm_arg} | grep "^--dry-run" > /dev/null 2> /dev/null; then
    drm_dry_run=true
    drm_arg_consumed=true
  fi
  if echo ${drm_arg} | grep "^--image-name" > /dev/null 2> /dev/null; then
    drm_image_name=`echo ${drm_arg} | sed "s/^--image-name=//"`
    drm_arg_consumed=true
  fi
  if echo ${drm_arg} | grep "^--image-tag" > /dev/null 2> /dev/null; then
    drm_image_tag=`echo ${drm_arg} | sed "s/^--image-tag=//"`
    drm_arg_consumed=true
  fi
  if echo ${drm_arg} | grep "^--extra-args" > /dev/null 2> /dev/null; then
    drm_extra_args=`echo ${drm_arg} | sed "s/^--extra-args=//"`
    drm_arg_consumed=true
  fi
  if [ "x${drm_arg_consumed}" == "x" ]; then
    echo "Unknown argument: \"${drm_arg}\""
    echo
    drm_usage
    exit 1
  fi
done

# remove the image if it already exists
if docker images | grep "${drm_image_name}:${drm_image_tag}" > /dev/null 2> /dev/null; then
  if [ "x${drm_verbose}" != "x" ]; then
    echo "Removing image \"${drm_image_name}:${drm_image_tag}\""
  fi
  if [ "x${drm_dry_run}" == "x" ]; then
    docker rmi "${drm_image_name}:${drm_image_tag}"
  fi
fi

# create docker build directory with Dockerfile
drm_tempdir=`mktemp -d`
if [ "x${drm_verbose}" != "x" ]; then
  echo "Docker build directory: ${drm_tempdir}"
fi
cp ${drm_wd}/scripts/Dockerfile ${drm_tempdir}/.

# add all enabled scripts
drm_scripts=( `find ${drm_wd}/scripts/enabled/. -maxdepth 1 -not -type d -printf '%f\n' | sort` )
if [ ${#drm_scripts[@]} -ne 0 ]; then
  # script directory need to be created in container
  command="`cat <<EOF
# run additional build scripts
RUN mkdir /root/docker-scripts/
@@scripts@@
EOF
`"
  sed --in-place "s|@@scripts@@|`echo "${command}" | sed '{:q;N;s/\n/\\\\n/g;t q}'`|" ${drm_tempdir}/Dockerfile

  # all enabled scripts need to be added to container and executed during build
  for drm_script in "${drm_scripts[@]}"; do
    command="`cat <<EOF
ADD ./${drm_script} /root/docker-scripts/
RUN /root/docker-scripts/${drm_script}
@@scripts@@
EOF
`"
    sed --in-place "s|@@scripts@@|`echo "${command}" | sed '{:q;N;s/\n/\\\\n/g;t q}'`|" ${drm_tempdir}/Dockerfile
    cp ${drm_wd}/scripts/enabled/${drm_script} ${drm_tempdir}/.
    if [ "x${drm_verbose}" != "x" ]; then
      echo "Added script: ${drm_script}"
    fi
  done
fi
# remove @@scripts@@ wildcard in Dockerfile
sed --in-place "s|@@scripts@@||" ${drm_tempdir}/Dockerfile

# build image
docker_build_command="docker build --rm=true --tag=\"${drm_image_name}:${drm_image_tag}\""
if [ "x${drm_extra_args}" != "x" ]; then
  docker_build_command="${docker_build_command} ${drm_extra_args}"
fi
docker_build_command="${docker_build_command} ${drm_tempdir}"
if [ "x${drm_verbose}" != "x" ]; then
  echo "Building image \"${drm_image_name}:${drm_image_tag}\": ${docker_build_command}"
fi
if [ "x${drm_dry_run}" == "x" ]; then
  eval "${docker_build_command}"
fi

# clean up
rm -rf ${drm_tempdir}


# vim: set ts=2 sw=2 et:


