#!/bin/bash

# Sets up default configuration of build scripts.

# auxiliary function to print out usage help
function drm_usage()
{
    cat <<EOF
Restores configuration of custom scripts.

BEWARE: THIS WILL DELETE ALL FILES PRESENT IN scripts/enabled DIRECTORY!

Usage: ${0} [options]

Options:

  --help                      print this help

  --version                   print version

EOF
}

# parse arguments
for drm_arg in "${@}"; do
  drm_arg_consumed=
  if echo ${drm_arg} | grep "^--help" > /dev/null 2> /dev/null; then
    drm_usage
    exit 0
  fi
  if echo ${drm_arg} | grep "^--version" > /dev/null 2> /dev/null; then
    echo "drm-reset-defaults v0.2.0"
    exit 0
  fi
  if [ "x${drm_arg_consumed}" == "x" ]; then
    echo "Unknown argument: \"${drm_arg}\""
    echo
    drm_usage
    exit 1
  fi
done

# determine script working directory
if [ "x${drm_wd}" == "x" ]; then
  drm_wd="`echo ${0} | sed -n '/\//{s/\/[^\/]*$//;p;}'`"
  drm_wd="`(cd "${drm_wd}/../..";pwd)`"
fi

# clean enabled scripts
rm ${drm_wd}/scripts/enabled/* > /dev/null 2> /dev/null

# restore defaults
cd ${drm_wd}/scripts/enabled
ln -s -v ../available/locale-en-gb-utf8.sh 10_locale-en-gb-utf8.sh
ln -s -v ../available/devel-cpp.sh 20_devel-cpp.sh
ln -s -v ../available/environment-vim.sh 30_environment-vim.sh
ln -s -v ../available/users-default.sh 40_users-default.sh
ln -s -v ../available/users-custom.sh 50_users-custom.sh


# vim: set ts=2 sw=2 et:


